id = "al"
name = "AL Language (Business Central)"
version = "0.1.0"
schema_version = 1
authors = ["Brad Fullwood"]
description = "AL language support for Microsoft Dynamics 365 Business Central"
repository = "https://github.com/Brad-Fullwood/zed-al"
languages = ["languages/al"]
snippets = ["snippets/al.json", "snippets/json.json"]
themes = ["themes/bc-themes.json"]

[lib]
kind = "Rust"
version = "0.8.0"

[language_servers.al-lsp]
name = "AL Language Server"
languages = ["AL"]

[debug_adapters.al]

[debug_locators.al]

[grammars.al]
repository = "https://github.com/Brad-Fullwood/AL-Tree-Sitter"
rev = "8d3cceae5459d5b1efa37e17d2dcee3186e111df"
