[package]
name = "al-core"
version = "0.1.0"
edition = "2021"

[dependencies]
al-syntax = { path = "../al-syntax" }
al-symbols = { path = "../al-symbols" }
al-semantic = { path = "../al-semantic" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
urlencoding = "2"
