[package]
name = "al-core"
version = "0.1.0"
edition = "2021"

[dependencies]
al-protocol = { path = "../al-protocol" }
al-syntax = { path = "../al-syntax" }
al-symbols = { path = "../al-symbols" }
al-semantic = { path = "../al-semantic" }
al-dap-client = { path = "../al-dap-client" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
dashmap = { workspace = true }
ropey = { workspace = true }
tracing = { workspace = true }
tree-sitter = "0.25"
url = "2"
petgraph = { workspace = true }

[dev-dependencies]
tempfile = "3"
