name = "AL"
grammar = "al"
path_suffixes = ["al"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
autoclose_before = ";:.,=}])<>\" \n\t"
word_characters = ["_"]
language_servers = ["al-lsp"]
